spring:
  application:
    name: new_personal_platform
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   #配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/wj?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1120
springfox:
  documentation:
    swagger-ui:
      #开启swagger配置 生产环境需关闭
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

client:
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDmbLy9ALRFKJYIRkBPfshC6Ki+HJHNpI9imZDZ6w47rwQoDsKMxE6h31uRtXROE/683N5orGavmCd7Bereg9TfNF2of6Q7TRB5JUJPgR2kNpDJ0OvSj1/KcqFzBmRrbf5NcUSJGGqmJjLD3iriqRCKqmIyqEgCM0tN8Nccgo+sBwIDAQAB
server:
  private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAOZsvL0AtEUolghGQE9+yELoqL4ckc2kj2KZkNnrDjuvBCgOwozETqHfW5G1dE4T/rzc3misZq+YJ3sF6t6D1N80Xah/pDtNEHklQk+BHaQ2kMnQ69KPX8pyoXMGZGtt/k1xRIkYaqYmMsPeKuKpEIqqYjKoSAIzS03w1xyCj6wHAgMBAAECgYEAt4PUkWaVLBtV2kMxBt7/WaJ4eejBCpnMBIgvgA8fp9MMqWaP9ZKG2Y7NG+/7MA/mqr3xeEYOBj1U/DrLQuqVxqdi9BwE+RaSTS9aNJUYPBsHpejt70K5Wfm0d5BRYjlF+BZt9oVn/Fc5YRsJlicOm0w+Lf6OSciY4VtaAsyGUjECQQD+XFPX6mTGscn3+1MTMPQup8pK+JzCa33Cnrj6lo2s5Z6X8mqTfOxtaUYsBCgDa4SOpljPt8iWMn3AeGD7pPn5AkEA5+jq6kv7eqBKYKMhdBDtZuP8YGLFa9aqvA3sPeBYLAcDujhNG2bfVvgsEzOoKv6OoEVO+JqzJbu3t+T82tNV/wJBAOfqcp/JHP11GPs7cXFsDxeC8RUOPI+fxlhus6X3I1HjQoi0BKxZGJBhjhOP7pO/smsGDK/Hl+IqQzH8ECEhOLECQGsQbOOeEIucVLooldkvt2o49trIvrv6bvhCtT4bxJkO4/mk5HQyGgncqPx0bL7spov3c23yfaJ992M+pD2iM6ECQDoorUpgHC2uLPnkvMrAPOU16lZGn4NldBI2VR8Ez8ZCJCmBX7iBky0+8NpZFg6O8oy1tdALrHVot+DXKn1l928=
